# Generated by Django 2.0.1 on 2018-02-10 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0006_auto_20171126_1853'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['owner', 'name']},
        ),
        migrations.AlterModelOptions(
            name='accounttype',
            options={'ordering': ['owner', 'name']},
        ),
        migrations.AlterModelOptions(
            name='budget',
            options={'ordering': ['owner', 'account']},
        ),
        migrations.AlterModelOptions(
            name='currency',
            options={'ordering': ['owner', 'code'], 'verbose_name_plural': 'Currencies'},
        ),
        migrations.AlterModelOptions(
            name='settings',
            options={'ordering': ['owner'], 'verbose_name_plural': 'Settings'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['owner', 'name']},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['owner', 'when']},
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='occurred',
            new_name='when',
        ),
    ]
