# Generated by Django 2.0.1 on 2018-02-10 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0007_auto_20180210_1208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['owner', '-when']},
        ),
    ]
