# Generated by Django 2.0.1 on 2018-02-10 22:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('money', '0008_auto_20180210_1653'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='currency',
            unique_together={('owner', 'code')},
        ),
    ]
