# Generated by Django 2.0.3 on 2018-06-01 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0009_auto_20180210_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='abbreviation',
        ),
    ]
