# Generated by Django 2.0.3 on 2018-06-01 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0010_remove_account_abbreviation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
