# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 18:13
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benny', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=22),
        ),
    ]
