# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 16:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('benny', '0003_auto_20161125_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='accountType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='benny.AccountType'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='credit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_transactions', to='benny.Account'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='debit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debit_transactions', to='benny.Account'),
        ),
    ]
