# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 17:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benny', '0004_auto_20161125_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
