# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 19:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('benny', '0006_auto_20161127_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='accountType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='benny.AccountType', verbose_name='Account type'),
        ),
    ]
