# Generated by Django 2.0.2 on 2019-04-05 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DictEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.CharField(max_length=63)),
                ('foreign', models.CharField(max_length=127)),
                ('example', models.CharField(max_length=255)),
            ],
        ),
    ]
