# Generated by Django 2.0.3 on 2018-06-01 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('okane', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name_plural': 'Currencies'},
        ),
    ]
